# Generated by Django 5.2.16 on 2026-07-10 09:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_registrationsettings_emailconfirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('login', 'Login'), ('registration', 'Registrierung')], max_length=30)),
                ('key_hash', models.CharField(max_length=64)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('window_started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('blocked_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Rate-Limit',
                'verbose_name_plural': 'Rate-Limits',
                'ordering': ['-updated_at', 'scope'],
                'constraints': [models.UniqueConstraint(fields=('scope', 'key_hash'), name='unique_rate_limit_scope_key')],
            },
        ),
    ]
