# Generated by Django 5.2.16 on 2026-07-09 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('disabled', 'Registrierung deaktiviert'), ('admin_approval', 'Registrierung mit Admin-Freigabe'), ('email_confirmation', 'Registrierung mit E-Mail-Bestaetigung'), ('automatic', 'Registrierung mit automatischer Aktivierung')], default='disabled', max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registrierung',
                'verbose_name_plural': 'Registrierung',
            },
        ),
        migrations.CreateModel(
            name='EmailConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_confirmations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'E-Mail-Bestaetigung',
                'verbose_name_plural': 'E-Mail-Bestaetigungen',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
