# Generated by Django 5.2.16 on 2026-07-09 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120)),
                ('title', models.CharField(max_length=180)),
                ('current_revision', models.PositiveIntegerField(default=0)),
                ('current_hash', models.CharField(blank=True, max_length=64)),
                ('change_note', models.CharField(blank=True, max_length=255)),
                ('last_edited_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_topics', to=settings.AUTH_USER_MODEL)),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_topics', to=settings.AUTH_USER_MODEL)),
                ('web', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='webs.web')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['web__slug', 'slug'],
                'constraints': [models.UniqueConstraint(fields=('web', 'slug'), name='unique_topic_slug_per_web')],
            },
        ),
    ]
