# Generated by Django 5.2.16 on 2026-07-10 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#176b87', max_length=7)),
                ('page_background_color', models.CharField(default='#f6f7f9', max_length=7)),
                ('surface_color', models.CharField(default='#ffffff', max_length=7)),
                ('text_color', models.CharField(default='#1f2933', max_length=7)),
                ('muted_text_color', models.CharField(default='#617184', max_length=7)),
                ('border_color', models.CharField(default='#d9dee7', max_length=7)),
                ('font_size_base', models.PositiveSmallIntegerField(default=16, validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(20)])),
                ('page_max_width', models.PositiveSmallIntegerField(default=1120, validators=[django.core.validators.MinValueValidator(960), django.core.validators.MaxValueValidator(1920)])),
                ('content_max_width', models.PositiveSmallIntegerField(default=1120, validators=[django.core.validators.MinValueValidator(560), django.core.validators.MaxValueValidator(1600)])),
                ('sidebar_left_width', models.PositiveSmallIntegerField(default=240, validators=[django.core.validators.MinValueValidator(180), django.core.validators.MaxValueValidator(400)])),
                ('sidebar_right_width', models.PositiveSmallIntegerField(default=240, validators=[django.core.validators.MinValueValidator(180), django.core.validators.MaxValueValidator(400)])),
                ('radius_strength', models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('left_sidebar_enabled', models.BooleanField(default=False)),
                ('right_sidebar_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Theme-Einstellungen',
                'verbose_name_plural': 'Theme-Einstellungen',
            },
        ),
    ]
