# Generated by Django 5.2.16 on 2026-07-09 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('private', 'Privat'), ('public', 'Oeffentlich lesbar'), ('authenticated', 'Nur registrierte Benutzer'), ('groups', 'Nur bestimmte Gruppen'), ('users', 'Nur bestimmte Benutzer')], default='private', max_length=20)),
                ('is_admin_web', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_webs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_webs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Web',
                'verbose_name_plural': 'Webs',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='WebPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(choices=[('user', 'Benutzer'), ('group', 'Gruppe'), ('authenticated', 'Registrierte Benutzer'), ('public', 'Oeffentliche Gaeste')], max_length=20)),
                ('subject_key', models.CharField(editable=False, max_length=191)),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_comment', models.BooleanField(default=False)),
                ('can_upload', models.BooleanField(default=False)),
                ('can_manage', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='web_permissions', to='auth.group')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='web_permissions', to=settings.AUTH_USER_MODEL)),
                ('web', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='webs.web')),
            ],
            options={
                'verbose_name': 'Web-Recht',
                'verbose_name_plural': 'Web-Rechte',
                'ordering': ['web__slug', 'subject_type', 'subject_key'],
                'constraints': [models.UniqueConstraint(fields=('web', 'subject_key'), name='unique_web_permission_subject'), models.CheckConstraint(condition=models.Q(models.Q(('group__isnull', True), ('subject_type', 'user'), ('user__isnull', False)), models.Q(('group__isnull', False), ('subject_type', 'group'), ('user__isnull', True)), models.Q(('group__isnull', True), ('subject_type', 'authenticated'), ('user__isnull', True)), models.Q(('group__isnull', True), ('subject_type', 'public'), ('user__isnull', True)), _connector='OR'), name='valid_web_permission_subject')],
            },
        ),
    ]
