# Generated by Django 5.2.16 on 2026-07-09 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0001_initial'),
        ('webs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_id_snapshot', models.BigIntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('action', models.CharField(choices=[('login_success', 'Login erfolgreich'), ('login_failed', 'Login fehlgeschlagen'), ('logout', 'Logout'), ('user_registered', 'Benutzer registriert'), ('user_approved', 'Benutzer freigeschaltet'), ('web_created', 'Web erstellt'), ('web_updated', 'Web geaendert'), ('permissions_updated', 'Rechte geaendert'), ('topic_created', 'Topic erstellt'), ('topic_updated', 'Topic geaendert'), ('topic_deleted', 'Topic geloescht'), ('revision_restored', 'Revision wiederhergestellt'), ('attachment_uploaded', 'Attachment hochgeladen'), ('attachment_updated', 'Attachment geaendert'), ('attachment_deleted', 'Attachment geloescht'), ('comment_created', 'Kommentar erstellt'), ('comment_deleted', 'Kommentar geloescht'), ('search_index_updated', 'Suchindex aktualisiert')], db_index=True, max_length=60)),
                ('web_slug', models.CharField(blank=True, max_length=80)),
                ('topic_slug', models.CharField(blank=True, max_length=120)),
                ('attachment_name', models.CharField(blank=True, max_length=255)),
                ('old_revision', models.PositiveIntegerField(blank=True, null=True)),
                ('new_revision', models.PositiveIntegerField(blank=True, null=True)),
                ('old_hash', models.CharField(blank=True, max_length=64)),
                ('new_hash', models.CharField(blank=True, max_length=64)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='topics.topic')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('web', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='webs.web')),
            ],
            options={
                'verbose_name': 'Auditlog',
                'verbose_name_plural': 'Auditlogs',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['web_slug', 'topic_slug'], name='audit_audit_web_slu_014a34_idx'), models.Index(fields=['created_at', 'action'], name='audit_audit_created_c61682_idx')],
            },
        ),
    ]
