# Generated by Django 5.2.16 on 2026-07-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login_success', 'Login erfolgreich'), ('login_failed', 'Login fehlgeschlagen'), ('logout', 'Logout'), ('user_registered', 'Benutzer registriert'), ('user_approved', 'Benutzer freigeschaltet'), ('web_created', 'Web erstellt'), ('web_updated', 'Web geaendert'), ('permissions_updated', 'Rechte geaendert'), ('topic_created', 'Topic erstellt'), ('topic_updated', 'Topic geaendert'), ('topic_deleted', 'Topic geloescht'), ('revision_restored', 'Revision wiederhergestellt'), ('attachment_uploaded', 'Attachment hochgeladen'), ('attachment_updated', 'Attachment geaendert'), ('attachment_deleted', 'Attachment geloescht'), ('comment_created', 'Kommentar erstellt'), ('comment_deleted', 'Kommentar geloescht'), ('search_index_updated', 'Suchindex aktualisiert'), ('rate_limit_blocked', 'Rate-Limit ausgeloest')], db_index=True, max_length=60),
        ),
    ]
